# Site
title:              'ZENVENT'
bio:                'Think. Build. Create.'
description:        'ZENVENT'
locale:             en_US
baseurl:            ""
url:                "https://www.zenvent.com"

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: 'zac'

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   zenvent

# Social
analytics-id:       "UA-122048100-1"
facebook:           https://facebook.com/https://www.facebook.com/THEZENVENT/
linkedin:           https://www.linkedin.com/in/zacrabtree/
github:             https://github.com/zenvent
youtube:            https://www.youtube.com/user/zenvent/

# personal
email:              zac@zenvent.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
